version: '3'
services:
  redis:
    image: redis
  db:
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: hour-work
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  server:
    image: server
    ports:
      - '4000:4000'
    depends_on:
      - redis
      - db
  web:
    image: web
    ports:
      - '3000:3000'
  proxy:
    image: abiosoft/caddy:no-stats
    volumes:
      - /root/benawad.com/Caddyfile:/etc/Caddyfile
      - /root/.caddy:/root/.caddy
      - /root/logs:/etc/logs
      - /root/goaccess/.html:/site/goaccess
    ports:
      - '80:80'
      - '443:443'
      - '7890:7890'
    depends_on:
      - web
      - server
  goaccess:
    image: allinurl/goaccess
    volumes:
      - /root/hour-work.ru/goaccess/data/:/srv/data
      - /root/goaccess/.html:/srv/report
      - /root/logs:/srv/logs
    depends_on:
      - proxy
